[package]
name = "polars_ds"
version = "0.1.0"
edition = "2021"

[lib]
name = "polars_ds"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = {version = "*", features = ["extension-module"]}
pyo3-polars = {version = "*", features = ["derive"]}
polars = {version = "*", features = ["fmt", "performant", "chunked_ids", "lazy", "zip_with", "random"]}
polars-core = "*"
polars-lazy = "*"
num = "0.4.1"

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }