[build-system]
requires = ["maturin>=1.2,<2.0"]
build-backend = "maturin"

[project]
name = "polars_ds"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
version = "0.1.0"
authors = [
    {name = "Tianren Qin", email = "tq9695@gmail.com"}
]
dependencies = [
    "polars >= 0.19.12",
] 

keywords = ["polars-extension", "scientific-computing"]

# [tool.maturin]
# python-source = "python"
# features = ["pyo3/extension-module"]
# module-name = "polars_ds._polars_ds"

[project.optional-dependencies]
dev = [
    "pytest >= 7.4.1",
]


[tool.ruff]
line-length = 120
fix = true
src = ["python"]